#ifndef _SHCOLL_ALLTOALL_H
#define _SHCOLL_ALLTOALL_H 1

#define SHCOLL_ALLTOALL_DECLARATION(_name, _type, _algo)                \
    void                                                                \
    shcoll_##_name##_alltoall_##_algo(shmem_team_t team,                \
                                               _type *dest,             \
                                               const _type *source,     \
                                               size_t nelems);          \

SHCOLL_ALLTOALL_DECLARATION(float, float, shift_exchange_barrier)
SHCOLL_ALLTOALL_DECLARATION(float, float, shift_exchange_barrier)
SHCOLL_ALLTOALL_DECLARATION(double, double, shift_exchange_barrier)
SHCOLL_ALLTOALL_DECLARATION(longdouble, long double, shift_exchange_barrier)
SHCOLL_ALLTOALL_DECLARATION(char, char, shift_exchange_barrier)
SHCOLL_ALLTOALL_DECLARATION(schar, signed char, shift_exchange_barrier)
SHCOLL_ALLTOALL_DECLARATION(short, short, shift_exchange_barrier)
SHCOLL_ALLTOALL_DECLARATION(int, int, shift_exchange_barrier)
SHCOLL_ALLTOALL_DECLARATION(long, long, shift_exchange_barrier)
SHCOLL_ALLTOALL_DECLARATION(longlong, long long, shift_exchange_barrier)
SHCOLL_ALLTOALL_DECLARATION(uchar, unsigned char, shift_exchange_barrier)
SHCOLL_ALLTOALL_DECLARATION(ushort, unsigned short, shift_exchange_barrier)
SHCOLL_ALLTOALL_DECLARATION(uint, unsigned int, shift_exchange_barrier)
SHCOLL_ALLTOALL_DECLARATION(ulong, unsigned long, shift_exchange_barrier)
SHCOLL_ALLTOALL_DECLARATION(ulonglong, unsigned long long, shift_exchange_barrier)
SHCOLL_ALLTOALL_DECLARATION(int8, int8_t, shift_exchange_barrier)
SHCOLL_ALLTOALL_DECLARATION(int16, int16_t, shift_exchange_barrier)
SHCOLL_ALLTOALL_DECLARATION(int32, int32_t, shift_exchange_barrier)
SHCOLL_ALLTOALL_DECLARATION(int64, int64_t, shift_exchange_barrier)
SHCOLL_ALLTOALL_DECLARATION(uint8, uint8_t, shift_exchange_barrier)
SHCOLL_ALLTOALL_DECLARATION(uint16, uint16_t, shift_exchange_barrier)
SHCOLL_ALLTOALL_DECLARATION(uint32, uint32_t, shift_exchange_barrier)
SHCOLL_ALLTOALL_DECLARATION(uint64, uint64_t, shift_exchange_barrier)
SHCOLL_ALLTOALL_DECLARATION(size, size_t, shift_exchange_barrier)
SHCOLL_ALLTOALL_DECLARATION(ptrdiff, ptrdiff_t, shift_exchange_barrier)

SHCOLL_ALLTOALL_DECLARATION(float, float, shift_exchange_counter)
SHCOLL_ALLTOALL_DECLARATION(float, float, shift_exchange_counter)
SHCOLL_ALLTOALL_DECLARATION(double, double, shift_exchange_counter)
SHCOLL_ALLTOALL_DECLARATION(longdouble, long double, shift_exchange_counter)
SHCOLL_ALLTOALL_DECLARATION(char, char, shift_exchange_counter)
SHCOLL_ALLTOALL_DECLARATION(schar, signed char, shift_exchange_counter)
SHCOLL_ALLTOALL_DECLARATION(short, short, shift_exchange_counter)
SHCOLL_ALLTOALL_DECLARATION(int, int, shift_exchange_counter)
SHCOLL_ALLTOALL_DECLARATION(long, long, shift_exchange_counter)
SHCOLL_ALLTOALL_DECLARATION(longlong, long long, shift_exchange_counter)
SHCOLL_ALLTOALL_DECLARATION(uchar, unsigned char, shift_exchange_counter)
SHCOLL_ALLTOALL_DECLARATION(ushort, unsigned short, shift_exchange_counter)
SHCOLL_ALLTOALL_DECLARATION(uint, unsigned int, shift_exchange_counter)
SHCOLL_ALLTOALL_DECLARATION(ulong, unsigned long, shift_exchange_counter)
SHCOLL_ALLTOALL_DECLARATION(ulonglong, unsigned long long, shift_exchange_counter)
SHCOLL_ALLTOALL_DECLARATION(int8, int8_t, shift_exchange_counter)
SHCOLL_ALLTOALL_DECLARATION(int16, int16_t, shift_exchange_counter)
SHCOLL_ALLTOALL_DECLARATION(int32, int32_t, shift_exchange_counter)
SHCOLL_ALLTOALL_DECLARATION(int64, int64_t, shift_exchange_counter)
SHCOLL_ALLTOALL_DECLARATION(uint8, uint8_t, shift_exchange_counter)
SHCOLL_ALLTOALL_DECLARATION(uint16, uint16_t, shift_exchange_counter)
SHCOLL_ALLTOALL_DECLARATION(uint32, uint32_t, shift_exchange_counter)
SHCOLL_ALLTOALL_DECLARATION(uint64, uint64_t, shift_exchange_counter)
SHCOLL_ALLTOALL_DECLARATION(size, size_t, shift_exchange_counter)
SHCOLL_ALLTOALL_DECLARATION(ptrdiff, ptrdiff_t, shift_exchange_counter)

SHCOLL_ALLTOALL_DECLARATION(float, float, shift_exchange_signal)
SHCOLL_ALLTOALL_DECLARATION(float, float, shift_exchange_signal)
SHCOLL_ALLTOALL_DECLARATION(double, double, shift_exchange_signal)
SHCOLL_ALLTOALL_DECLARATION(longdouble, long double, shift_exchange_signal)
SHCOLL_ALLTOALL_DECLARATION(char, char, shift_exchange_signal)
SHCOLL_ALLTOALL_DECLARATION(schar, signed char, shift_exchange_signal)
SHCOLL_ALLTOALL_DECLARATION(short, short, shift_exchange_signal)
SHCOLL_ALLTOALL_DECLARATION(int, int, shift_exchange_signal)
SHCOLL_ALLTOALL_DECLARATION(long, long, shift_exchange_signal)
SHCOLL_ALLTOALL_DECLARATION(longlong, long long, shift_exchange_signal)
SHCOLL_ALLTOALL_DECLARATION(uchar, unsigned char, shift_exchange_signal)
SHCOLL_ALLTOALL_DECLARATION(ushort, unsigned short, shift_exchange_signal)
SHCOLL_ALLTOALL_DECLARATION(uint, unsigned int, shift_exchange_signal)
SHCOLL_ALLTOALL_DECLARATION(ulong, unsigned long, shift_exchange_signal)
SHCOLL_ALLTOALL_DECLARATION(ulonglong, unsigned long long, shift_exchange_signal)
SHCOLL_ALLTOALL_DECLARATION(int8, int8_t, shift_exchange_signal)
SHCOLL_ALLTOALL_DECLARATION(int16, int16_t, shift_exchange_signal)
SHCOLL_ALLTOALL_DECLARATION(int32, int32_t, shift_exchange_signal)
SHCOLL_ALLTOALL_DECLARATION(int64, int64_t, shift_exchange_signal)
SHCOLL_ALLTOALL_DECLARATION(uint8, uint8_t, shift_exchange_signal)
SHCOLL_ALLTOALL_DECLARATION(uint16, uint16_t, shift_exchange_signal)
SHCOLL_ALLTOALL_DECLARATION(uint32, uint32_t, shift_exchange_signal)
SHCOLL_ALLTOALL_DECLARATION(uint64, uint64_t, shift_exchange_signal)
SHCOLL_ALLTOALL_DECLARATION(size, size_t, shift_exchange_signal)
SHCOLL_ALLTOALL_DECLARATION(ptrdiff, ptrdiff_t, shift_exchange_signal)

SHCOLL_ALLTOALL_DECLARATION(float, float, color_pairwise_exchange_signal)
SHCOLL_ALLTOALL_DECLARATION(float, float, color_pairwise_exchange_signal)
SHCOLL_ALLTOALL_DECLARATION(double, double, color_pairwise_exchange_signal)
SHCOLL_ALLTOALL_DECLARATION(longdouble, long double, color_pairwise_exchange_signal)
SHCOLL_ALLTOALL_DECLARATION(char, char, color_pairwise_exchange_signal)
SHCOLL_ALLTOALL_DECLARATION(schar, signed char, color_pairwise_exchange_signal)
SHCOLL_ALLTOALL_DECLARATION(short, short, color_pairwise_exchange_signal)
SHCOLL_ALLTOALL_DECLARATION(int, int, color_pairwise_exchange_signal)
SHCOLL_ALLTOALL_DECLARATION(long, long, color_pairwise_exchange_signal)
SHCOLL_ALLTOALL_DECLARATION(longlong, long long, color_pairwise_exchange_signal)
SHCOLL_ALLTOALL_DECLARATION(uchar, unsigned char, color_pairwise_exchange_signal)
SHCOLL_ALLTOALL_DECLARATION(ushort, unsigned short, color_pairwise_exchange_signal)
SHCOLL_ALLTOALL_DECLARATION(uint, unsigned int, color_pairwise_exchange_signal)
SHCOLL_ALLTOALL_DECLARATION(ulong, unsigned long, color_pairwise_exchange_signal)
SHCOLL_ALLTOALL_DECLARATION(ulonglong, unsigned long long, color_pairwise_exchange_signal)
SHCOLL_ALLTOALL_DECLARATION(int8, int8_t, color_pairwise_exchange_signal)
SHCOLL_ALLTOALL_DECLARATION(int16, int16_t, color_pairwise_exchange_signal)
SHCOLL_ALLTOALL_DECLARATION(int32, int32_t, color_pairwise_exchange_signal)
SHCOLL_ALLTOALL_DECLARATION(int64, int64_t, color_pairwise_exchange_signal)
SHCOLL_ALLTOALL_DECLARATION(uint8, uint8_t, color_pairwise_exchange_signal)
SHCOLL_ALLTOALL_DECLARATION(uint16, uint16_t, color_pairwise_exchange_signal)
SHCOLL_ALLTOALL_DECLARATION(uint32, uint32_t, color_pairwise_exchange_signal)
SHCOLL_ALLTOALL_DECLARATION(uint64, uint64_t, color_pairwise_exchange_signal)
SHCOLL_ALLTOALL_DECLARATION(size, size_t, color_pairwise_exchange_signal)
SHCOLL_ALLTOALL_DECLARATION(ptrdiff, ptrdiff_t, color_pairwise_exchange_signal)

SHCOLL_ALLTOALL_DECLARATION(float, float, xor_pairwise_exchange_barrier)
SHCOLL_ALLTOALL_DECLARATION(float, float, xor_pairwise_exchange_barrier)
SHCOLL_ALLTOALL_DECLARATION(double, double, xor_pairwise_exchange_barrier)
SHCOLL_ALLTOALL_DECLARATION(longdouble, long double, xor_pairwise_exchange_barrier)
SHCOLL_ALLTOALL_DECLARATION(char, char, xor_pairwise_exchange_barrier)
SHCOLL_ALLTOALL_DECLARATION(schar, signed char, xor_pairwise_exchange_barrier)
SHCOLL_ALLTOALL_DECLARATION(short, short, xor_pairwise_exchange_barrier)
SHCOLL_ALLTOALL_DECLARATION(int, int, xor_pairwise_exchange_barrier)
SHCOLL_ALLTOALL_DECLARATION(long, long, xor_pairwise_exchange_barrier)
SHCOLL_ALLTOALL_DECLARATION(longlong, long long, xor_pairwise_exchange_barrier)
SHCOLL_ALLTOALL_DECLARATION(uchar, unsigned char, xor_pairwise_exchange_barrier)
SHCOLL_ALLTOALL_DECLARATION(ushort, unsigned short, xor_pairwise_exchange_barrier)
SHCOLL_ALLTOALL_DECLARATION(uint, unsigned int, xor_pairwise_exchange_barrier)
SHCOLL_ALLTOALL_DECLARATION(ulong, unsigned long, xor_pairwise_exchange_barrier)
SHCOLL_ALLTOALL_DECLARATION(ulonglong, unsigned long long, xor_pairwise_exchange_barrier)
SHCOLL_ALLTOALL_DECLARATION(int8, int8_t, xor_pairwise_exchange_barrier)
SHCOLL_ALLTOALL_DECLARATION(int16, int16_t, xor_pairwise_exchange_barrier)
SHCOLL_ALLTOALL_DECLARATION(int32, int32_t, xor_pairwise_exchange_barrier)
SHCOLL_ALLTOALL_DECLARATION(int64, int64_t, xor_pairwise_exchange_barrier)
SHCOLL_ALLTOALL_DECLARATION(uint8, uint8_t, xor_pairwise_exchange_barrier)
SHCOLL_ALLTOALL_DECLARATION(uint16, uint16_t, xor_pairwise_exchange_barrier)
SHCOLL_ALLTOALL_DECLARATION(uint32, uint32_t, xor_pairwise_exchange_barrier)
SHCOLL_ALLTOALL_DECLARATION(uint64, uint64_t, xor_pairwise_exchange_barrier)
SHCOLL_ALLTOALL_DECLARATION(size, size_t, xor_pairwise_exchange_barrier)
SHCOLL_ALLTOALL_DECLARATION(ptrdiff, ptrdiff_t, xor_pairwise_exchange_barrier)

SHCOLL_ALLTOALL_DECLARATION(float, float, xor_pairwise_exchange_counter)
SHCOLL_ALLTOALL_DECLARATION(float, float, xor_pairwise_exchange_counter)
SHCOLL_ALLTOALL_DECLARATION(double, double, xor_pairwise_exchange_counter)
SHCOLL_ALLTOALL_DECLARATION(longdouble, long double, xor_pairwise_exchange_counter)
SHCOLL_ALLTOALL_DECLARATION(char, char, xor_pairwise_exchange_counter)
SHCOLL_ALLTOALL_DECLARATION(schar, signed char, xor_pairwise_exchange_counter)
SHCOLL_ALLTOALL_DECLARATION(short, short, xor_pairwise_exchange_counter)
SHCOLL_ALLTOALL_DECLARATION(int, int, xor_pairwise_exchange_counter)
SHCOLL_ALLTOALL_DECLARATION(long, long, xor_pairwise_exchange_counter)
SHCOLL_ALLTOALL_DECLARATION(longlong, long long, xor_pairwise_exchange_counter)
SHCOLL_ALLTOALL_DECLARATION(uchar, unsigned char, xor_pairwise_exchange_counter)
SHCOLL_ALLTOALL_DECLARATION(ushort, unsigned short, xor_pairwise_exchange_counter)
SHCOLL_ALLTOALL_DECLARATION(uint, unsigned int, xor_pairwise_exchange_counter)
SHCOLL_ALLTOALL_DECLARATION(ulong, unsigned long, xor_pairwise_exchange_counter)
SHCOLL_ALLTOALL_DECLARATION(ulonglong, unsigned long long, xor_pairwise_exchange_counter)
SHCOLL_ALLTOALL_DECLARATION(int8, int8_t, xor_pairwise_exchange_counter)
SHCOLL_ALLTOALL_DECLARATION(int16, int16_t, xor_pairwise_exchange_counter)
SHCOLL_ALLTOALL_DECLARATION(int32, int32_t, xor_pairwise_exchange_counter)
SHCOLL_ALLTOALL_DECLARATION(int64, int64_t, xor_pairwise_exchange_counter)
SHCOLL_ALLTOALL_DECLARATION(uint8, uint8_t, xor_pairwise_exchange_counter)
SHCOLL_ALLTOALL_DECLARATION(uint16, uint16_t, xor_pairwise_exchange_counter)
SHCOLL_ALLTOALL_DECLARATION(uint32, uint32_t, xor_pairwise_exchange_counter)
SHCOLL_ALLTOALL_DECLARATION(uint64, uint64_t, xor_pairwise_exchange_counter)
SHCOLL_ALLTOALL_DECLARATION(size, size_t, xor_pairwise_exchange_counter)
SHCOLL_ALLTOALL_DECLARATION(ptrdiff, ptrdiff_t, xor_pairwise_exchange_counter)

SHCOLL_ALLTOALL_DECLARATION(float, float, xor_pairwise_exchange_signal)
SHCOLL_ALLTOALL_DECLARATION(float, float, xor_pairwise_exchange_signal)
SHCOLL_ALLTOALL_DECLARATION(double, double, xor_pairwise_exchange_signal)
SHCOLL_ALLTOALL_DECLARATION(longdouble, long double, xor_pairwise_exchange_signal)
SHCOLL_ALLTOALL_DECLARATION(char, char, xor_pairwise_exchange_signal)
SHCOLL_ALLTOALL_DECLARATION(schar, signed char, xor_pairwise_exchange_signal)
SHCOLL_ALLTOALL_DECLARATION(short, short, xor_pairwise_exchange_signal)
SHCOLL_ALLTOALL_DECLARATION(int, int, xor_pairwise_exchange_signal)
SHCOLL_ALLTOALL_DECLARATION(long, long, xor_pairwise_exchange_signal)
SHCOLL_ALLTOALL_DECLARATION(longlong, long long, xor_pairwise_exchange_signal)
SHCOLL_ALLTOALL_DECLARATION(uchar, unsigned char, xor_pairwise_exchange_signal)
SHCOLL_ALLTOALL_DECLARATION(ushort, unsigned short, xor_pairwise_exchange_signal)
SHCOLL_ALLTOALL_DECLARATION(uint, unsigned int, xor_pairwise_exchange_signal)
SHCOLL_ALLTOALL_DECLARATION(ulong, unsigned long, xor_pairwise_exchange_signal)
SHCOLL_ALLTOALL_DECLARATION(ulonglong, unsigned long long, xor_pairwise_exchange_signal)
SHCOLL_ALLTOALL_DECLARATION(int8, int8_t, xor_pairwise_exchange_signal)
SHCOLL_ALLTOALL_DECLARATION(int16, int16_t, xor_pairwise_exchange_signal)
SHCOLL_ALLTOALL_DECLARATION(int32, int32_t, xor_pairwise_exchange_signal)
SHCOLL_ALLTOALL_DECLARATION(int64, int64_t, xor_pairwise_exchange_signal)
SHCOLL_ALLTOALL_DECLARATION(uint8, uint8_t, xor_pairwise_exchange_signal)
SHCOLL_ALLTOALL_DECLARATION(uint16, uint16_t, xor_pairwise_exchange_signal)
SHCOLL_ALLTOALL_DECLARATION(uint32, uint32_t, xor_pairwise_exchange_signal)
SHCOLL_ALLTOALL_DECLARATION(uint64, uint64_t, xor_pairwise_exchange_signal)
SHCOLL_ALLTOALL_DECLARATION(size, size_t, xor_pairwise_exchange_signal)
SHCOLL_ALLTOALL_DECLARATION(ptrdiff, ptrdiff_t, xor_pairwise_exchange_signal)

SHCOLL_ALLTOALL_DECLARATION(float, float, color_pairwise_exchange_barrier)
SHCOLL_ALLTOALL_DECLARATION(float, float, color_pairwise_exchange_barrier)
SHCOLL_ALLTOALL_DECLARATION(double, double, color_pairwise_exchange_barrier)
SHCOLL_ALLTOALL_DECLARATION(longdouble, long double, color_pairwise_exchange_barrier)
SHCOLL_ALLTOALL_DECLARATION(char, char, color_pairwise_exchange_barrier)
SHCOLL_ALLTOALL_DECLARATION(schar, signed char, color_pairwise_exchange_barrier)
SHCOLL_ALLTOALL_DECLARATION(short, short, color_pairwise_exchange_barrier)
SHCOLL_ALLTOALL_DECLARATION(int, int, color_pairwise_exchange_barrier)
SHCOLL_ALLTOALL_DECLARATION(long, long, color_pairwise_exchange_barrier)
SHCOLL_ALLTOALL_DECLARATION(longlong, long long, color_pairwise_exchange_barrier)
SHCOLL_ALLTOALL_DECLARATION(uchar, unsigned char, color_pairwise_exchange_barrier)
SHCOLL_ALLTOALL_DECLARATION(ushort, unsigned short, color_pairwise_exchange_barrier)
SHCOLL_ALLTOALL_DECLARATION(uint, unsigned int, color_pairwise_exchange_barrier)
SHCOLL_ALLTOALL_DECLARATION(ulong, unsigned long, color_pairwise_exchange_barrier)
SHCOLL_ALLTOALL_DECLARATION(ulonglong, unsigned long long, color_pairwise_exchange_barrier)
SHCOLL_ALLTOALL_DECLARATION(int8, int8_t, color_pairwise_exchange_barrier)
SHCOLL_ALLTOALL_DECLARATION(int16, int16_t, color_pairwise_exchange_barrier)
SHCOLL_ALLTOALL_DECLARATION(int32, int32_t, color_pairwise_exchange_barrier)
SHCOLL_ALLTOALL_DECLARATION(int64, int64_t, color_pairwise_exchange_barrier)
SHCOLL_ALLTOALL_DECLARATION(uint8, uint8_t, color_pairwise_exchange_barrier)
SHCOLL_ALLTOALL_DECLARATION(uint16, uint16_t, color_pairwise_exchange_barrier)
SHCOLL_ALLTOALL_DECLARATION(uint32, uint32_t, color_pairwise_exchange_barrier)
SHCOLL_ALLTOALL_DECLARATION(uint64, uint64_t, color_pairwise_exchange_barrier)
SHCOLL_ALLTOALL_DECLARATION(size, size_t, color_pairwise_exchange_barrier)
SHCOLL_ALLTOALL_DECLARATION(ptrdiff, ptrdiff_t, color_pairwise_exchange_barrier)

SHCOLL_ALLTOALL_DECLARATION(float, float, color_pairwise_exchange_counter)
SHCOLL_ALLTOALL_DECLARATION(float, float, color_pairwise_exchange_counter)
SHCOLL_ALLTOALL_DECLARATION(double, double, color_pairwise_exchange_counter)
SHCOLL_ALLTOALL_DECLARATION(longdouble, long double, color_pairwise_exchange_counter)
SHCOLL_ALLTOALL_DECLARATION(char, char, color_pairwise_exchange_counter)
SHCOLL_ALLTOALL_DECLARATION(schar, signed char, color_pairwise_exchange_counter)
SHCOLL_ALLTOALL_DECLARATION(short, short, color_pairwise_exchange_counter)
SHCOLL_ALLTOALL_DECLARATION(int, int, color_pairwise_exchange_counter)
SHCOLL_ALLTOALL_DECLARATION(long, long, color_pairwise_exchange_counter)
SHCOLL_ALLTOALL_DECLARATION(longlong, long long, color_pairwise_exchange_counter)
SHCOLL_ALLTOALL_DECLARATION(uchar, unsigned char, color_pairwise_exchange_counter)
SHCOLL_ALLTOALL_DECLARATION(ushort, unsigned short, color_pairwise_exchange_counter)
SHCOLL_ALLTOALL_DECLARATION(uint, unsigned int, color_pairwise_exchange_counter)
SHCOLL_ALLTOALL_DECLARATION(ulong, unsigned long, color_pairwise_exchange_counter)
SHCOLL_ALLTOALL_DECLARATION(ulonglong, unsigned long long, color_pairwise_exchange_counter)
SHCOLL_ALLTOALL_DECLARATION(int8, int8_t, color_pairwise_exchange_counter)
SHCOLL_ALLTOALL_DECLARATION(int16, int16_t, color_pairwise_exchange_counter)
SHCOLL_ALLTOALL_DECLARATION(int32, int32_t, color_pairwise_exchange_counter)
SHCOLL_ALLTOALL_DECLARATION(int64, int64_t, color_pairwise_exchange_counter)
SHCOLL_ALLTOALL_DECLARATION(uint8, uint8_t, color_pairwise_exchange_counter)
SHCOLL_ALLTOALL_DECLARATION(uint16, uint16_t, color_pairwise_exchange_counter)
SHCOLL_ALLTOALL_DECLARATION(uint32, uint32_t, color_pairwise_exchange_counter)
SHCOLL_ALLTOALL_DECLARATION(uint64, uint64_t, color_pairwise_exchange_counter)
SHCOLL_ALLTOALL_DECLARATION(size, size_t, color_pairwise_exchange_counter)
SHCOLL_ALLTOALL_DECLARATION(ptrdiff, ptrdiff_t, color_pairwise_exchange_counter)

SHCOLL_ALLTOALL_DECLARATION(float, float, color_pairwise_exchange_signal)
SHCOLL_ALLTOALL_DECLARATION(float, float, color_pairwise_exchange_signal)
SHCOLL_ALLTOALL_DECLARATION(double, double, color_pairwise_exchange_signal)
SHCOLL_ALLTOALL_DECLARATION(longdouble, long double, color_pairwise_exchange_signal)
SHCOLL_ALLTOALL_DECLARATION(char, char, color_pairwise_exchange_signal)
SHCOLL_ALLTOALL_DECLARATION(schar, signed char, color_pairwise_exchange_signal)
SHCOLL_ALLTOALL_DECLARATION(short, short, color_pairwise_exchange_signal)
SHCOLL_ALLTOALL_DECLARATION(int, int, color_pairwise_exchange_signal)
SHCOLL_ALLTOALL_DECLARATION(long, long, color_pairwise_exchange_signal)
SHCOLL_ALLTOALL_DECLARATION(longlong, long long, color_pairwise_exchange_signal)
SHCOLL_ALLTOALL_DECLARATION(uchar, unsigned char, color_pairwise_exchange_signal)
SHCOLL_ALLTOALL_DECLARATION(ushort, unsigned short, color_pairwise_exchange_signal)
SHCOLL_ALLTOALL_DECLARATION(uint, unsigned int, color_pairwise_exchange_signal)
SHCOLL_ALLTOALL_DECLARATION(ulong, unsigned long, color_pairwise_exchange_signal)
SHCOLL_ALLTOALL_DECLARATION(ulonglong, unsigned long long, color_pairwise_exchange_signal)
SHCOLL_ALLTOALL_DECLARATION(int8, int8_t, color_pairwise_exchange_signal)
SHCOLL_ALLTOALL_DECLARATION(int16, int16_t, color_pairwise_exchange_signal)
SHCOLL_ALLTOALL_DECLARATION(int32, int32_t, color_pairwise_exchange_signal)
SHCOLL_ALLTOALL_DECLARATION(int64, int64_t, color_pairwise_exchange_signal)
SHCOLL_ALLTOALL_DECLARATION(uint8, uint8_t, color_pairwise_exchange_signal)
SHCOLL_ALLTOALL_DECLARATION(uint16, uint16_t, color_pairwise_exchange_signal)
SHCOLL_ALLTOALL_DECLARATION(uint32, uint32_t, color_pairwise_exchange_signal)
SHCOLL_ALLTOALL_DECLARATION(uint64, uint64_t, color_pairwise_exchange_signal)
SHCOLL_ALLTOALL_DECLARATION(size, size_t, color_pairwise_exchange_signal)
SHCOLL_ALLTOALL_DECLARATION(ptrdiff, ptrdiff_t, color_pairwise_exchange_signal)


#endif /* ! _SHCOLL_ALLTOALL_H */
